/*
 * REST API Decoder
 *
 * REST API Versions
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ContentSummaryDTO : IEquatable<ContentSummaryDTO>
    {
        public ContentSummaryDTO(long? from, long? to, int? reports, Dictionary<string, int?> contents)
        {
            From = from;
            To = to;
            Reports = reports;
            Contents = contents;
        }
        public ContentSummaryDTO()
        {
            From = 0;
            To = 0;
            Reports = 0;
            Contents = new Dictionary<string, int?>();
        }

        /// <summary>
        /// Gets or Sets From
        /// </summary>

        [DataMember(Name="from")]
        public long? From { get; set; }

        /// <summary>
        /// Gets or Sets To
        /// </summary>

        [DataMember(Name="to")]
        public long? To { get; set; }

        /// <summary>
        /// Gets or Sets Reports
        /// </summary>

        [DataMember(Name="reports")]
        public int? Reports { get; set; }

        /// <summary>
        /// Gets or Sets Contents
        /// </summary>

        [DataMember(Name="contents")]
        public Dictionary<string, int?> Contents { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ContentSummaryDTO {\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("  Reports: ").Append(Reports).Append("\n");
            sb.Append("  Contents: ").Append(Contents).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ContentSummaryDTO)obj);
        }

        /// <summary>
        /// Returns true if ContentSummaryDTO instances are equal
        /// </summary>
        /// <param name="other">Instance of ContentSummaryDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ContentSummaryDTO other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    From == other.From ||
                    From != null &&
                    From.Equals(other.From)
                ) && 
                (
                    To == other.To ||
                    To != null &&
                    To.Equals(other.To)
                ) && 
                (
                    Reports == other.Reports ||
                    Reports != null &&
                    Reports.Equals(other.Reports)
                ) && 
                (
                    Contents == other.Contents ||
                    Contents != null &&
                    Contents.SequenceEqual(other.Contents)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (From != null)
                    hashCode = hashCode * 59 + From.GetHashCode();
                    if (To != null)
                    hashCode = hashCode * 59 + To.GetHashCode();
                    if (Reports != null)
                    hashCode = hashCode * 59 + Reports.GetHashCode();
                    if (Contents != null)
                    hashCode = hashCode * 59 + Contents.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ContentSummaryDTO left, ContentSummaryDTO right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ContentSummaryDTO left, ContentSummaryDTO right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
