/*
 * REST API Decoder
 *
 * REST API Versions
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ImfAttachmentDTO : IEquatable<ImfAttachmentDTO>
    { 
        /// <summary>
        /// Gets or Sets Path
        /// </summary>
        [Required]

        [DataMember(Name="path")]
        public string Path { get; set; }

        /// <summary>
        /// Gets or Sets Filename
        /// </summary>

        [DataMember(Name="filename")]
        public string Filename { get; set; }

        /// <summary>
        /// Gets or Sets ContentType
        /// </summary>
        [Required]

        [DataMember(Name="contentType")]
        public string ContentType { get; set; }

        /// <summary>
        /// Gets or Sets ContentEncoding
        /// </summary>

        [DataMember(Name="contentEncoding")]
        public string ContentEncoding { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ImfAttachmentDTO {\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("  Filename: ").Append(Filename).Append("\n");
            sb.Append("  ContentType: ").Append(ContentType).Append("\n");
            sb.Append("  ContentEncoding: ").Append(ContentEncoding).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ImfAttachmentDTO)obj);
        }

        /// <summary>
        /// Returns true if ImfAttachmentDTO instances are equal
        /// </summary>
        /// <param name="other">Instance of ImfAttachmentDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ImfAttachmentDTO other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Path == other.Path ||
                    Path != null &&
                    Path.Equals(other.Path)
                ) && 
                (
                    Filename == other.Filename ||
                    Filename != null &&
                    Filename.Equals(other.Filename)
                ) && 
                (
                    ContentType == other.ContentType ||
                    ContentType != null &&
                    ContentType.Equals(other.ContentType)
                ) && 
                (
                    ContentEncoding == other.ContentEncoding ||
                    ContentEncoding != null &&
                    ContentEncoding.Equals(other.ContentEncoding)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Path != null)
                    hashCode = hashCode * 59 + Path.GetHashCode();
                    if (Filename != null)
                    hashCode = hashCode * 59 + Filename.GetHashCode();
                    if (ContentType != null)
                    hashCode = hashCode * 59 + ContentType.GetHashCode();
                    if (ContentEncoding != null)
                    hashCode = hashCode * 59 + ContentEncoding.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ImfAttachmentDTO left, ImfAttachmentDTO right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ImfAttachmentDTO left, ImfAttachmentDTO right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
