/*
 * REST API Decoder
 *
 * REST API Versions
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Pleskalizer.Common.Enums;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class L7ConversationStatisticsListDTO : IEquatable<L7ConversationStatisticsListDTO>
    {
        public L7ConversationStatisticsListDTO(Guid? captureId, string addressA, string addressB, int? portA, int? portB, ProtocolL3Enum? protocolL3, ProtocolL4Enum? protocolL4, string protocolL7, Guid? sessionId)
        {
            CaptureId = captureId;
            AddressA = addressA;
            AddressB = addressB;
            PortA = portA;
            PortB = portB;
            ProtocolL3 = protocolL3;
            ProtocolL4 = protocolL4;
            ProtocolL7 = protocolL7;
            SessionId = sessionId;
        }

        public L7ConversationStatisticsListDTO()
        {
            CaptureId = Guid.NewGuid();
            AddressA = String.Empty;
            AddressB = String.Empty;
            PortA = 0;
            PortB = 0;
            ProtocolL3 = 0;
            ProtocolL4 = 0;
            ProtocolL7 = String.Empty;
            SessionId = Guid.NewGuid();
        }

        /// <summary>
        /// Gets or Sets CaptureId
        /// </summary>
        [Required]

        [DataMember(Name="captureId")]
        public Guid? CaptureId { get; set; }

        /// <summary>
        /// Gets or Sets AddressA
        /// </summary>
        [Required]

        [DataMember(Name="addressA")]
        public string AddressA { get; set; }

        /// <summary>
        /// Gets or Sets AddressB
        /// </summary>
        [Required]

        [DataMember(Name="addressB")]
        public string AddressB { get; set; }

        /// <summary>
        /// Gets or Sets PortA
        /// </summary>
        [Required]

        [DataMember(Name="portA")]
        public int? PortA { get; set; }

        /// <summary>
        /// Gets or Sets PortB
        /// </summary>
        [Required]

        [DataMember(Name="portB")]
        public int? PortB { get; set; }



        /// <summary>
        /// Gets or Sets ProtocolL3
        /// </summary>
        [Required]

        [DataMember(Name="protocolL3")]
        public ProtocolL3Enum? ProtocolL3 { get; set; }


        /// <summary>
        /// Gets or Sets ProtocolL4
        /// </summary>
        [Required]

        [DataMember(Name="protocolL4")]
        public ProtocolL4Enum? ProtocolL4 { get; set; }

        /// <summary>
        /// Gets or Sets ProtocolL7
        /// </summary>
        [Required]

        [DataMember(Name="protocolL7")]
        public string ProtocolL7 { get; set; }

        /// <summary>
        /// Gets or Sets SessionId
        /// </summary>
        [Required]

        [DataMember(Name="sessionId")]
        public Guid? SessionId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class L7ConversationStatisticsListDTO {\n");
            sb.Append("  CaptureId: ").Append(CaptureId).Append("\n");
            sb.Append("  AddressA: ").Append(AddressA).Append("\n");
            sb.Append("  AddressB: ").Append(AddressB).Append("\n");
            sb.Append("  PortA: ").Append(PortA).Append("\n");
            sb.Append("  PortB: ").Append(PortB).Append("\n");
            sb.Append("  ProtocolL3: ").Append(ProtocolL3).Append("\n");
            sb.Append("  ProtocolL4: ").Append(ProtocolL4).Append("\n");
            sb.Append("  ProtocolL7: ").Append(ProtocolL7).Append("\n");
            sb.Append("  SessionId: ").Append(SessionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((L7ConversationStatisticsListDTO)obj);
        }

        /// <summary>
        /// Returns true if L7ConversationStatisticsListDTO instances are equal
        /// </summary>
        /// <param name="other">Instance of L7ConversationStatisticsListDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(L7ConversationStatisticsListDTO other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    CaptureId == other.CaptureId ||
                    CaptureId != null &&
                    CaptureId.Equals(other.CaptureId)
                ) && 
                (
                    AddressA == other.AddressA ||
                    AddressA != null &&
                    AddressA.Equals(other.AddressA)
                ) && 
                (
                    AddressB == other.AddressB ||
                    AddressB != null &&
                    AddressB.Equals(other.AddressB)
                ) && 
                (
                    PortA == other.PortA ||
                    PortA != null &&
                    PortA.Equals(other.PortA)
                ) && 
                (
                    PortB == other.PortB ||
                    PortB != null &&
                    PortB.Equals(other.PortB)
                ) && 
                (
                    ProtocolL3 == other.ProtocolL3 ||
                    ProtocolL3 != null &&
                    ProtocolL3.Equals(other.ProtocolL3)
                ) && 
                (
                    ProtocolL4 == other.ProtocolL4 ||
                    ProtocolL4 != null &&
                    ProtocolL4.Equals(other.ProtocolL4)
                ) && 
                (
                    ProtocolL7 == other.ProtocolL7 ||
                    ProtocolL7 != null &&
                    ProtocolL7.Equals(other.ProtocolL7)
                ) && 
                (
                    SessionId == other.SessionId ||
                    SessionId != null &&
                    SessionId.Equals(other.SessionId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (CaptureId != null)
                    hashCode = hashCode * 59 + CaptureId.GetHashCode();
                    if (AddressA != null)
                    hashCode = hashCode * 59 + AddressA.GetHashCode();
                    if (AddressB != null)
                    hashCode = hashCode * 59 + AddressB.GetHashCode();
                    if (PortA != null)
                    hashCode = hashCode * 59 + PortA.GetHashCode();
                    if (PortB != null)
                    hashCode = hashCode * 59 + PortB.GetHashCode();
                    if (ProtocolL3 != null)
                    hashCode = hashCode * 59 + ProtocolL3.GetHashCode();
                    if (ProtocolL4 != null)
                    hashCode = hashCode * 59 + ProtocolL4.GetHashCode();
                    if (ProtocolL7 != null)
                    hashCode = hashCode * 59 + ProtocolL7.GetHashCode();
                    if (SessionId != null)
                    hashCode = hashCode * 59 + SessionId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(L7ConversationStatisticsListDTO left, L7ConversationStatisticsListDTO right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(L7ConversationStatisticsListDTO left, L7ConversationStatisticsListDTO right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
