'''
* Project: interpret.py
* interpreting IPPcode22
* 2021/2022
* @author Marek Klofera <xklofe01@stud.fit.vutbr.cz> - VUT FIT student
'''

# GLOBALS
ROOT_ATTRIBUTES = ["LANGUAGE", "NAME", "DESCRIPTION"]
HEADER = "IPPCODE22"
INSTRUCTION_ATTRIBUTES = ["ORDER", "OPCODE"]
INSTRUCTIONS = [
    "MOVE", "CREATEFRAME", "PUSHFRAME", "POPFRAME", "DEFVAR", "CALL", "RETURN", "PUSHS", "POPS",
    "ADD", "SUB", "MUL", "IDIV", "LT", "GT", "EQ", "AND", "OR", "NOT", "INT2CHAR", "STRI2INT",
    "READ", "WRITE", "CONCAT", "STRLEN", "GETCHAR", "SETCHAR", "TYPE", "LABEL", "JUMP", "JUMPIFEQ",
    "JUMPIFNEQ", "EXIT", "DPRINT", "BREAK", "INT2FLOAT", "FLOAT2INT", "DIV"
]


ARG_NUMBERS = ["1", "2", "3"]
ARG_TYPES = ["INT", "BOOL", "STRING", "NIL", "LABEL", "TYPE", "VAR", "FLOAT"]
ARG_ATTRIBUTE = "TYPE"

INSTRUCTIONS_WITH_ZERO_ARG = ["CREATEFRAME", "PUSHFRAME", "POPFRAME", "RETURN", "BREAK"]
INSTRUCTIONS_WITH_ONE_ARG = ["PUSHS", "WRITE", "EXIT", "DPRINT", "CALL", "LABEL", "JUMP", "DEFVAR", "POPS"]
INSTRUCTIONS_WITH_TWO_ARG = ["MOVE", "INT2CHAR", "STRLEN", "NOT", "TYPE", "READ"]
INSTRUCTIONS_WITH_THREE_ARG = [
    "ADD", "SUB", "MUL", "IDIV", "LT", "GT", "EQ", "AND", "OR", "STRI2INT", "CONCAT",
    "GETCHAR", "SETCHAR", "JUMPIFEQ", "JUMPIFNEQ"
]
