# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: Use .Net 7.0
  inputs:
    version: '7.0.x'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Publish .NET
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/FoodDelivery.Api.App.csproj'
    arguments: '--output $(Build.ArtifactStagingDirectory)/api'
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/api'
    ArtifactName: 'API'
    publishLocation: 'Container'
