//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDelivery.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AllergenResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AllergenResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodDelivery.Common.Resources.AllergenResources", typeof(AllergenResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celery.
        /// </summary>
        internal static string CeleryDescription {
            get {
                return ResourceManager.GetString("CeleryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crustaceans.
        /// </summary>
        internal static string CrustaceansDescription {
            get {
                return ResourceManager.GetString("CrustaceansDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eggs.
        /// </summary>
        internal static string EggsDescription {
            get {
                return ResourceManager.GetString("EggsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish.
        /// </summary>
        internal static string FishDescription {
            get {
                return ResourceManager.GetString("FishDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cereals containing gluten.
        /// </summary>
        internal static string GlutenDescription {
            get {
                return ResourceManager.GetString("GlutenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lupin.
        /// </summary>
        internal static string LupinDescription {
            get {
                return ResourceManager.GetString("LupinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milk.
        /// </summary>
        internal static string MilkDescription {
            get {
                return ResourceManager.GetString("MilkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molluscs.
        /// </summary>
        internal static string MolluscsDescription {
            get {
                return ResourceManager.GetString("MolluscsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mustard.
        /// </summary>
        internal static string MustardDescription {
            get {
                return ResourceManager.GetString("MustardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuts.
        /// </summary>
        internal static string NutsDescription {
            get {
                return ResourceManager.GetString("NutsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peanuts.
        /// </summary>
        internal static string PeanutsDescription {
            get {
                return ResourceManager.GetString("PeanutsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesame seeds.
        /// </summary>
        internal static string SesameDescription {
            get {
                return ResourceManager.GetString("SesameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soybeans.
        /// </summary>
        internal static string SoybeansDescription {
            get {
                return ResourceManager.GetString("SoybeansDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sulphur dioxide and sulphites.
        /// </summary>
        internal static string SulphurDescription {
            get {
                return ResourceManager.GetString("SulphurDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string UndefinedDescription {
            get {
                return ResourceManager.GetString("UndefinedDescription", resourceCulture);
            }
        }
    }
}
